### ISSUE TITLE
超出显存限制

### ISSUE THREAD

**Issue by Hitjss** [BXZZcj/TinyRobotBench#1]
非常感谢作者的贡献，我在3090Ti电脑上部署了模型，将llava7b移到了GPU上，遇到超出显存的问题，请问这个现象正常吗，您是使用的CPU进行的推理吗，谢谢您的回答

**Comment by BXZZcj** [comment]
> 非常感谢作者的贡献，我在3090Ti电脑上部署了模型，将llava7b移到了GPU上，遇到超出显存的问题，请问这个现象正常吗，您是使用的CPU进行的推理吗，谢谢您的回答

感谢你的提问。我没尝试过在3090Ti上部署模型，但我觉得超出显存应该是正常的。

事实上，我跑llava7b时是在4090上跑的。当我仅输入文本时，llava7b推理很慢；当我输入一张50*50的图片时并提问“图片中有什么”时，模型需要花费10分钟完成推理；当我输入两张50*50的图片时，即遇到超出显存的问题。

所以我认为你遇到的问题是正常的。

多提一嘴，我不建议用llava7b指导机器人做操作，它太弱了。我建议直接用ChatAnyWhere提供的gpt3.5 API，不需要自己部署LLMs，便宜，效果还好。

**Comment by Hitjss** [comment]
> > 非常感谢作者的贡献，我在3090Ti电脑上部署了模型，将llava7b移到了GPU上，遇到超出显存的问题，请问这个现象正常吗，您是使用的CPU进行的推理吗，谢谢您的回答
> 
> 感谢你的提问。我没尝试过在3090Ti上部署模型，但我觉得超出显存应该是正常的。
> 
> 事实上，我跑llava7b时是在4090上跑的。当我仅输入文本时，llava7b推理很慢;当我输入一张50_50的图片时并提问“图片中有什么”时，模型需要花费10分钟完成推理;当我输入两张50_50的图片时，即遇到超出显存的问题。
> 
> 所以我认为你遇到的问题是正常的。
> 
> 多提一嘴，我不建议用llava7b指导机器人做操作，它太弱了。我建议直接用ChatAnyWhere提供的gpt3.5 API，不需要自己部署LLMs，便宜，效果还好。

谢谢作者的回答！我尝试把您的项目跑通了，的确llava7b效果很不稳定，但是在研究您代码的同时我向您学习到了很多知识，再次向您表示感谢！可以冒昧的问一下您后来尝试增加其他API或者融入多模态信息进行优化的工作了吗

**Comment by BXZZcj** [comment]
> > > 非常感谢作者的贡献，我在3090Ti电脑上部署了模型，将llava7b移到了GPU上，遇到超出显存的问题，请问这个现象正常吗，您是使用的CPU进行的推理吗，谢谢您的回答
> > 
> > 
> > 感谢你的提问。我没尝试过在3090Ti上部署模型，但我觉得超出显存应该是正常的。
> > 事实上，我跑llava7b时是在4090上跑的。当我仅输入文本时，llava7b推理很慢;当我输入一张50_50的图片时并提问“图片中有什么”时，模型需要花费10分钟完成推理;当我输入两张50_50的图片时，即遇到超出显存的问题。
> > 所以我认为你遇到的问题是正常的。
> > 多提一嘴，我不建议用llava7b指导机器人做操作，它太弱了。我建议直接用ChatAnyWhere提供的gpt3.5 API，不需要自己部署LLMs，便宜，效果还好。
> 
> 谢谢作者的回答！我尝试把您的项目跑通了，的确llava7b效果很不稳定，但是在研究您代码的同时我向您学习到了很多知识，再次向您表示感谢！可以冒昧的问一下您后来尝试增加其他API或者融入多模态信息进行优化的工作了吗

你好，不客气，互相学习。

我后面有尝试增加其他API或者融入多模态信息进行优化的工作，但是在我另一个仓库中进行的：[BBSEA-sapien](https://github.com/BXZZcj/BBSEA-sapien)。关于BBSEA-sapien的初步pipeline可以参考该项目README中提到的论文[BBSEA](https://arxiv.org/abs/2402.08212)。事实上，我打算将BBSEA-sapien做成一个Embodied LLMs的评测平台。

需要注意的是：BBSEA-sapien尚在开发中，我预计在8月末上线一个用户友好的README。

**Comment by Hitjss** [comment]
> > > > 非常感谢作者的贡献，我在3090Ti电脑上部署了模型，将llava7b移到了GPU上，遇到超出显存的问题，请问这个现象正常吗，您是使用的CPU进行的推理吗，谢谢您的回答
> > > 
> > > 
> > > 感谢你的提问。我没尝试过在3090Ti上部署模型，但我觉得超出显存应该是正常的。
> > > 事实上，我跑llava7b时是在4090上跑的。当我仅输入文本时，llava7b推理很慢;当我输入一张50_50的图片时并提问“图片中有什么”时，模型需要花费10分钟完成推理;当我输入两张50_50的图片时，即遇到超出显存的问题。
> > > 所以我认为你遇到的问题是正常的。
> > > 多提一嘴，我不建议用llava7b指导机器人做操作，它太弱了。我建议直接用ChatAnyWhere提供的gpt3.5 API，不需要自己部署LLMs，便宜，效果还好。
> > 
> > 
> > 谢谢作者的回答！我尝试把您的项目跑通了，的确llava7b效果很不稳定，但是在研究您代码的同时我向您学习到了很多知识，再次向您表示感谢！可以冒昧的问一下您后来尝试增加其他API或者融入多模态信息进行优化的工作了吗
> 
> 你好，不客气，互相学习。
> 
> 我后面有尝试增加其他API或者融入多模态信息进行优化的工作，但是在我另一个仓库中进行的：[BBSEA-sapien](https://github.com/BXZZcj/BBSEA-sapien)。关于BBSEA-sapien的初步pipeline可以参考该项目README中提到的论文[BBSEA](https://arxiv.org/abs/2402.08212)。事实上，我打算将BBSEA-sapien做成一个Embodied LLMs的评测平台。
> 
> 需要注意的是：BBSEA-sapien尚在开发中，我预计在8月末上线一个用户友好的README。

太好了！期待您的新工作！我会持续关注您的！祝您科研顺利，成果多多。

**Comment by BXZZcj** [comment]
> > > > > 非常感谢作者的贡献，我在3090Ti电脑上部署了模型，将llava7b移到了GPU上，遇到超出显存的问题，请问这个现象正常吗，您是使用的CPU进行的推理吗，谢谢您的回答
> > > > 
> > > > 
> > > > 感谢你的提问。我没尝试过在3090Ti上部署模型，但我觉得超出显存应该是正常的。
> > > > 事实上，我跑llava7b时是在4090上跑的。当我仅输入文本时，llava7b推理很慢;当我输入一张50_50的图片时并提问“图片中有什么”时，模型需要花费10分钟完成推理;当我输入两张50_50的图片时，即遇到超出显存的问题。
> > > > 所以我认为你遇到的问题是正常的。
> > > > 多提一嘴，我不建议用llava7b指导机器人做操作，它太弱了。我建议直接用ChatAnyWhere提供的gpt3.5 API，不需要自己部署LLMs，便宜，效果还好。
> > > 
> > > 
> > > 谢谢作者的回答！我尝试把您的项目跑通了，的确llava7b效果很不稳定，但是在研究您代码的同时我向您学习到了很多知识，再次向您表示感谢！可以冒昧的问一下您后来尝试增加其他API或者融入多模态信息进行优化的工作了吗
> > 
> > 
> > 你好，不客气，互相学习。
> > 我后面有尝试增加其他API或者融入多模态信息进行优化的工作，但是在我另一个仓库中进行的：[BBSEA-sapien](https://github.com/BXZZcj/BBSEA-sapien)。关于BBSEA-sapien的初步pipeline可以参考该项目README中提到的论文[BBSEA](https://arxiv.org/abs/2402.08212)。事实上，我打算将BBSEA-sapien做成一个Embodied LLMs的评测平台。
> > 需要注意的是：BBSEA-sapien尚在开发中，我预计在8月末上线一个用户友好的README。
> 
> 太好了！期待您的新工作！我会持续关注您的！祝您科研顺利，成果多多。

谢谢！我也是初学者，共同进步☺️
